version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./db:/app/db
    command: >
      sh -c "python manage.py migrate &&
             gunicorn todo_challenge.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60"
    healthcheck:
      test: ["CMD", "python", "manage.py", "check"]
      interval: 30s
      timeout: 10s
      retries: 3
